app:
  loadUser: true
  totalOrdersCount: 20000
debug: false

server:
  port: 6222 

spring:
  datasource:
    url: jdbc:h2:mem:orders_db
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false