app:
  loadUser: true
debug: false

server:
  port: 8222 

spring:
  datasource:
    url: jdbc:h2:mem:orders_db
    username: sa
    password: welcome
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      properties:
        format_sql: true 
