app:
  loadUser: true
  totalOrdersCount: 200
debug: false

server:
  port: 8222 

spring:
  datasource:
    url: jdbc:h2:mem:orders_db
    username: sa
    password: welcome
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false