app:
  loadUser: true
  totalOrdersCount: 20
debug: false

server:
  port: 8222 

spring:
  datasource:
    url: jdbc:h2:mem:orders_db
    username: sa
    password: welcome
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

    shutdown:
      enabled: true